# Generated by Django 5.2 on 2025-06-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('caller_number', models.CharField(max_length=50)),
                ('main_path', models.CharField(choices=[('sales', 'Sales'), ('support', 'Support')], help_text='“sales” or “support”', max_length=20)),
                ('caller_type', models.CharField(choices=[('practitioner', 'Practitioner'), ('client', 'Client')], help_text='“practitioner” or “client”', max_length=20)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('practice_type', models.CharField(blank=True, max_length=255, null=True)),
                ('primary_interest', models.CharField(blank=True, max_length=500, null=True)),
                ('sales_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client_inquiry_focus', models.CharField(blank=True, max_length=500, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('account_identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('support_issue_summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('callback_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
