# Generated by Django 5.2 on 2025-06-08 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='callerinfo',
            name='account_identifier',
        ),
        migrations.RemoveField(
            model_name='callerinfo',
            name='call_id',
        ),
        migrations.RemoveField(
            model_name='callerinfo',
            name='callback_number',
        ),
        migrations.RemoveField(
            model_name='callerinfo',
            name='client_inquiry_focus',
        ),
        migrations.RemoveField(
            model_name='callerinfo',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='callerinfo',
            name='support_issue_summary',
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='caller_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='caller_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='main_path',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='practice_type',
            field=models.CharField(blank=True, default='physcio therapy', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='primary_interest',
            field=models.TextField(blank=True, default='abcd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='sales_email',
            field=models.EmailField(blank=True, default='abcd@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='transcript',
            field=models.TextField(blank=True, default='abcd'),
            preserve_default=False,
        ),
    ]
