# Generated by Django 5.2 on 2025-06-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_remove_callerinfo_account_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callerinfo',
            name='business_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
