# Generated by Django 5.2 on 2025-06-08 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0003_alter_callerinfo_business_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callerinfo',
            name='practice_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
