# Generated by Django 5.2 on 2025-06-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0004_alter_callerinfo_practice_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callerinfo',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='caller_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='main_path',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='practice_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='primary_interest',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='sales_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='transcript',
            field=models.TextField(blank=True, default=''),
        ),
    ]
