# Generated by Django 5.2 on 2025-06-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0005_alter_callerinfo_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callerinfo',
            name='business_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='caller_type',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='main_path',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='practice_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='primary_interest',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='sales_email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='callerinfo',
            name='transcript',
            field=models.TextField(blank=True),
        ),
    ]
